### ISSUE TITLE
What can be the possible reason for Invalid keystore format error

### ISSUE THREAD

**Issue by rambo236817** [ctron/pem-keystore#7]
getting this error even after specifying the property -- spring.cloud.vault.ssl.key-store=./vault-keystore.properties

Caused by: java.lang.IllegalStateException: java.io.IOException: Invalid keystore format
	at org.springframework.vault.client.ClientHttpConnectorFactory.configureSsl(ClientHttpConnectorFactory.java:122) ~[spring-vault-core-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.vault.client.ClientHttpConnectorFactory.access$000(ClientHttpConnectorFactory.java:52) ~[spring-vault-core-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	

what could be the possible reason for this

**Comment by ctron** [comment]
I don't know about this property, sorry. Are you sure the underlying implementing uses the "PEM keystore" implementation that this library provides?
